version: '3.8'
services:
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /backend/node_modules
    depends_on:
      - backend
    command: /bin/sh -c "npm ci && npm run dev"
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: /bin/sh -c "npm ci && npx nodemon src/server.js"

